apiVersion: v1
kind: Pod
metadata:
  name: client-billy
spec:
  restartPolicy: Never
  runtimeClassName: gvisor
  containers:
    - name: run
      image: ko://github.com/wlynch/levias/client
      #args: ["run", "cgr.dev/chainguard/bash", "echo hello"]
      args: ["levias-daemon"]
      resources:
        limits:
          cpu: 2
          ephemeral-storage: 10Gi
          memory: 10Gi
      env:
        - name: LEVIAS_URL
          value: "http://levias-server.default.svc.cluster.local"
