apiVersion: v1
kind: Pod
metadata:
  name: client-billy
spec:
  restartPolicy: Never
  containers:
    # - name: run
    #   image: ko://github.com/wlynch/levias/client
    #   args: ["run", "cgr.dev/chainguard/bash", "echo hello"]
    #   env:
    #     - name: LEVIAS_URL
    #       value: "http://levias-server.default.svc.cluster.local"
    - name: build
      image: ko://github.com/wlynch/levias/client
      command: ["sh"]
      args: ["-c", 'echo "FROM scratch" | client build -; sleep 600']
      env:
        - name: LEVIAS_URL
          value: "http://levias-server.default.svc.cluster.local"
