apiVersion: v1
kind: Pod
metadata:
  name: forever
spec:
  containers:
  - name: sleep
    image: cgr.dev/chainguard/bash
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]