apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-service-account-issuer-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: levias-server
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/attach", "pods/ephemeralcontainers", "pods/exec"]
    verbs: ["create", "update", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: levias-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: levias-server
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
